title: Welcome to the DWD homepage!
description: This is my homepage for project information and contact details
show_downloads: true
theme: jekyll-theme-cayman
google_analytics:

exclude: ['Collaborations.txt','Notes.txt']

